### ISSUE TITLE
Improve CreateGroup with owners/members on first call

### ISSUE THREAD

**Issue by wobba** [CrayonAS/Cumulus.Monads#1]
See https://github.com/SharePoint/PnP-Sites-Core/pull/1990 for reference code.

Instead of adding owners/members after the group is created it's better to add them at the same time. Extend code to allow for owners/members, but should not be required for backwards compability.

**Comment by Abdullahiibrahimahmed** [comment]
@wobba I improved the " CreateGroup with owners/members on first call #1 ".  I have cloned a copy of Cumulus.Monads but i add some functions i cannot push.

" remote: Permission to CrayonAS/Cumulus.Monads.git denied to Abdullahiibrahimahmed.
fatal: unable to access 'https://github.com/CrayonAS/Cumulus.Monads.git/': The requested URL returned error: 403"

**Comment by wobba** [comment]
@Abdullahiibrahimahmed You have yet to accept the invite: https://github.com/CrayonAS/Cumulus.Monads/settings/collaboration

**Comment by olemp** [comment]
Changes done by @Abdullahiibrahimahmed merged to dev. Will test in my own environment before merging to master.

**Comment by olemp** [comment]
@Abdullahiibrahimahmed Build fails with `CustomConnector.cs`:

![image](https://user-images.githubusercontent.com/7606007/49948805-6f71bb80-fef4-11e8-883a-72cfa96d8e29.png)

Had to comment it out for now
https://github.com/CrayonAS/Cumulus.Monads/pull/12/commits/6410a701d7ba6051e8d2f8ebb763f745c6fc8a91

Do you have any idea what's wrong?

**Comment by Abdullahiibrahimahmed** [comment]
just commit it, i will check it and let you know

**Comment by olemp** [comment]
https://github.com/CrayonAS/Cumulus.Monads/commit/a1afba857fa50c88f622e92147394cfc3b4a237f

**Comment by Abdullahiibrahimahmed** [comment]
@olemp  the Methods should be **interna**l instead of **private**.
 " **internal** static dynamic GenerateSecurityDefinitions() "
"**internal** static dynamic GeneratePaths(Assembly assembly, dynamic doc)"

That will solve the problem.

**Comment by olemp** [comment]
Cool. Fixed: https://github.com/CrayonAS/Cumulus.Monads/commit/d9eccc48f2d4e8540cd63e8044ddff0b4e380896

**Comment by olemp** [comment]
Merged to master: https://github.com/CrayonAS/Cumulus.Monads/pull/15
